### ISSUE TITLE
Math Rendering Improperly Renders Super and Subscripts

### ISSUE THREAD

**Issue by johnblommers** [kmwallio/ThiefMD#56]
The following examples:

```
$$f(x)=a_0+a_2x^2$$

$$x_{1,2}=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$
```

render badly as shown below:

![Screenshot from 2020-10-08 21-00-41](https://user-images.githubusercontent.com/8484427/95541918-7743ff00-09a9-11eb-95d4-31a37380e5d5.png)

The proper rendering is:

![Screenshot from 2020-10-08 21-03-24](https://user-images.githubusercontent.com/8484427/95542151-d7d33c00-09a9-11eb-8c5b-1dba4e7fc348.png)

**Comment by kmwallio** [comment]
This is fixed in the beta branch with the ability to change the preview CSS.

![math-css](https://user-images.githubusercontent.com/132455/95545625-4b2d7b80-09b3-11eb-9d3e-3cc7b5af134c.png)

It will be included in the next release.

I'm currently torn between having the default CSS be no-styling, or keeping the current one that breaks math rendering.  Feel free to let me know your thoughts. It's not immediately discoverable, so I'm leaning towards a more basic default style.

**Comment by johnblommers** [comment]
As of ThiefMD 0.1.2 this issue persists in the live preview.

The good news is that math formulas render fine in the export preview.

Good job keeping those updates coming!

**Comment by kmwallio** [comment]
Thanks! I'm still working on new default CSS. We started work on [Export CSS](https://themes.thiefmd.com/export-css/) support. This will adjust the default preview if you choose none or pick a different theme.

![export_preferences](https://user-images.githubusercontent.com/132455/97096320-4dccd980-161f-11eb-88e7-7a433aaefb85.png)

**Comment by johnblommers** [comment]
Excellent! Thanks for the tip.
